### ISSUE TITLE
I think the path names in the URLs should be same as in github or on local filesysteme

### ISSUE THREAD

**Issue by aboodman** [attic-labs/decent-website#10]
Right now, the URLs on the site are like `.../doc/about`, whereas the path names are actually `../doc/about.md`.

I think the pretty URLs are nice, and get the desire to have them. However they cause problems because developers don't think to check that they work when they are writing docs. Also in this particular case it is difficult because it changes the meaning of a link with a relative URL.

I think it would be simpler to just end the URLs with `.md`.

**Comment by jesseditson** [comment]
I like this idea, and considered it when working on the site, but the issue isn't just the extensions, the paths are in fact different. All the docs are under the `doc` folder, which is not on the website. Also, there are some special cases (demo-ipfs-chat.md and demo-p2p-chat.md) that are nested in the nav but not in the gh tree.

I figured it would be easier to maintain a list of mappings than come up with semi-generic rules, but it's likely easier just to let the URLs on the website be ugly but not break relative links. I'll pursue that option.
