### ISSUE TITLE
styles still need help

### ISSUE THREAD

**Issue by aboodman** [attic-labs/decent-website#13]
Some issues that I see

- [x] body copy is not correct color (too light)
- [x] highlighting on code is not correct
- [x] font size inconsistent (e.g., inside lists -- see http://noms.io/docs/decent/about/ and http://noms.io/docs/decent/quickstart/)
- [x] inline code formatting here (http://noms.io/docs/decent/quickstart/) is a mess
- [x] top margin on pages is too large (should be similar to left margin
- [x] something about weight and layout of navbar looks wrong -- ask @jennabilotta but my guess is weight is too heavy, font probably too big, and need to align with body copy.

**Comment by jennabilotta** [comment]
Re: the last bullet -- yes to all of that. It's both larger and heavier and has a much larger line height. I think just tugging on *one* of those strings is more than sufficient. I propose size (not weight, I'm anti-bold, it obscures the subtlety of the letterforms in bad ways) $.02

LMK if you need any specific specs

**Comment by jennabilotta** [comment]
also - the styles on <ul> are wonky (too large/heavy) see screenshot. Should be the same as body text using the slightly heavier weight for emphasis on the initial text. 
<img width="910" alt="screen shot 2017-09-21 at 10 53 53 am" src="https://user-images.githubusercontent.com/22665226/30710694-4288e2aa-9ebb-11e7-9fe2-34085371aa74.png">

**Comment by jennabilotta** [comment]
Last thing. It might help differentiate the sidebar menu typography to give it a *very* subtle bg color. Let's use the one from attic #f4f4f5 - only when it's open. I think that will help the eye understand that it's a separate segment without being overpowering. Maybe even a really subtle dropshadow from the body content bg (white) onto the sidebar bg (very light grey) to make it appear as if it's on "top" but slid over.

**Comment by jesseditson** [comment]
Fixed all these except ` highlighting on code is not correct` - I believe that is just a matter of not tagging the language and the auto-detection not having enough hints to figure it out. On the quickstart page things are working as expected, cause the blocks are created by doing:

```
```go
[code]
```

(note the `go` tag). If we update README.md to specify the language it should fix the issue. LMK if there's anywhere else you're seeing incorrect highlighting.

**Comment by jesseditson** [comment]
In the meantime I'll turn off language detection which should at least remove the incorrect highlights.

**Comment by jesseditson** [comment]
(quick follow up, looks like highlight.js doesn't have that option... gonna just annotate all the blocks instead)
